name: Publish Windows

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  publish_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: electron-build-win
          path: build/
      - name: List files for debugging
        run: ls -R build/
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: v1.0.0
          release_name: Release v1.0.0
          draft: false
          prerelease: false
      - name: Upload Release Asset (Windows)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/out/make/squirrel.windows/x64/invoice_gen-1.0.0 Setup.exe
          asset_name: invoice_gen-1.0.0-setup-win.exe
          asset_content_type: application/octet-stream
